CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL,
  "email" varchar(30) UNIQUE NOT NULL,
  "password" varchar(20) UNIQUE NOT NULL,
  "age" int NOT NULL,
  "id_roles" int NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "video_course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) UNIQUE NOT NULL,
  "url" varchar(35) UNIQUE NOT NULL
);

CREATE TABLE "course_general" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) UNIQUE NOT NULL,
  "description" varchar(50) UNIQUE NOT NULL,
  "id_level" int NOT NULL,
  "id_teacher" int NOT NULL,
  "id_user" int NOT NULL,
  "id_categories" int NOT NULL,
  "id_videos" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("id_roles") REFERENCES "roles" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_teacher") REFERENCES "teacher" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_videos") REFERENCES "video_course" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_categories") REFERENCES "categories" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_level") REFERENCES "level" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

/*Insert Roles*/

ntrega1=# INSERT INTO roles (name) VALUES ('Student');
INSERT 0 1
entrega1=# INSERT INTO roles (name) VALUES ('Teacher');
INSERT 0 1
entrega1=# INSERT INTO roles (name) VALUES ('Admin');
INSERT 0 1
entrega1=# SELECT * FROM roles;
 id |  name
----+---------
  1 | Student
  2 | Teacher
  3 | Admin
(3 filas)


/*Insert Users*/
entrega1=# INSERT INTO users (name,email,password,age,id_roles) VALUES ('Jorge','jorge@gmail.com','jorge12',20,1),('Laura','maria@gmail.com','laura12',22,1),('Andres','fer@gmail.com','andres12',45,2),('Alvaro','fran@gmail.com','alvaro12',46,3);
INSERT 0 4

entrega1=# SELECT * FROM users;
 id |  name  |      email      | password | age | id_roles
----+--------+-----------------+----------+-----+----------
  1 | Jorge  | jorge@gmail.com | jorge12  |  20 |        1
  2 | Laura  | maria@gmail.com | laura12  |  22 |        1
  3 | Andres | fer@gmail.com   | andres12 |  45 |        2
  4 | Alvaro | fran@gmail.com  | alvaro12 |  46 |        3
(4 filas)


entrega1=#
/*Insert Categories*/

entrega1=# INSERT INTO categories (name) VALUES ('Diseño UIX'),('Programacion'),('Seguridad');
INSERT 0 3
entrega1=# SELECT * FROM categories;
 id |     name
----+--------------
  1 | Diseño UIX
  2 | Programacion
  3 | Seguridad
(3 filas)

/*Insert Teacher*/

entrega1=# INSERT INTO teacher (name) VALUES ('Brenda'),('Iam'),('Andres');
INSERT 0 3
entrega1=# SELECT * FROM teacher;
 id |  name
----+--------
  1 | Brenda
  2 | Iam
  3 | Andres
(3 filas)

/*Insert Video_Course*/

entrega1=# INSERT INTO video_course (title,url) VALUES ('CSS','https://css.com'),('JavaScript','https://javascript.com'),('HTML','https://html.com'),('Ruby','https//ruby.com'),('React','https://react.com'),('Cybersecurity','https://cybersecurity');
INSERT 0 6
entrega1=# SELECT * FROM video_course;
 id |     title     |          url
----+---------------+------------------------
  1 | CSS           | https://css.com
  2 | JavaScript    | https://javascript.com
  3 | HTML          | https://html.com
  4 | Ruby          | https://ruby.com
  5 | React         | https://react.com
  6 | Cybersecurity | https://cybersecurity.com
(6 filas)

/*Insert Course_General*/

entrega1=#  INSERT INTO course_general (title,description,id_level,id_teacher,id_user,id_categories,id_videos) VALUES ('JavaScript','Tecnologias para controlar funcionalidades',3,2,2,2,2),('HTML','Maquetado Pagina web',2,3,1,2,3),('Ruby','Fundamentos Baiscos',1,1,2,1,4),('React','Redux, Reducer y Hooks',2,2,2,1,5),('Cybersecurity','Seguridad AWS',3,3,1,3,6);
INSERT 0 5
entrega1=# SELECT * FROM course_general;
 id |     title     |                description                 | id_level | id_teacher | id_user | id_categories | id_videos
----+---------------+--------------------------------------------+----------+------------+---------+---------------+-----------
 13 | CSS           | Tecnologias para estilar frontend          |        1 |          1 |       1 |             2 |         1
 14 | JavaScript    | Tecnologias para controlar funcionalidades |        3 |          2 |       2 |             2 |         2
 15 | HTML          | Maquetado Pagina web                       |        2 |          3 |       1 |             2 |         3
 16 | Ruby          | Fundamentos Baiscos                        |        1 |          1 |       2 |             1 |         4
 17 | React         | Redux, Reducer y Hooks                     |        2 |          2 |       2 |             1 |         5
 18 | Cybersecurity | Seguridad AWS                              |        3 |          3 |       1 |             3 |         6
(6 filas)

/*GENERAL-TABLE*/
entrega1=# SELECT course_general.id , course_general.title, course_general.description , level.name , users.name , categories.name, video_course.title, video_course.url, teacher.name FROM course_general JOIN level ON level.id=course_general.id_level JOIN users ON users.id=course_general.id_user JOIN categories ON categories.id=course_general.id_categories JOIN video_course ON video_course.id=course_general.id_videos JOIN teacher ON teacher.id=course_general.id_teacher;
 id |     title     |                description                 |     name      | name  |     name     |     title     |          url             |  name
----+---------------+--------------------------------------------+---------------+-------+--------------+---------------+--------------------------+--------
 13 | CSS           | Tecnologias para estilar frontend          | Principiantes | Jorge | Programacion | CSS           | https://css.com          | Brenda
 14 | JavaScript    | Tecnologias para controlar funcionalidades | Avanzado      | Laura | Programacion | JavaScript    | https://javascript.com   | Iam
 15 | HTML          | Maquetado Pagina web                       | Intermedio    | Jorge | Programacion | HTML          | https://html.com         | Andres
 16 | Ruby          | Fundamentos Baiscos                        | Principiantes | Laura | Diseño UIX   | Ruby          | https://ruby.com         | Brenda
 17 | React         | Redux, Reducer y Hooks                     | Intermedio    | Laura | Diseño UIX   | React         | https://react.com        | Iam
 18 | Cybersecurity | Seguridad AWS                              | Avanzado      | Jorge | Seguridad    | Cybersecurity | https://cybersecurity.com| Andres
(6 filas)


entrega1=#